server:
  port: 7777

spring:
  application:
    name: gateway-service
  datasource:
    url: jdbc:mysql://localhost:3306/auth_service
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/auth-service-keycloak

management:
  endpoints:
    web:
      exposure:
        include: mappings
