spring:
  application.name: db-migration
  datasource:
    url: jdbc:mysql://localhost:3306/auth_service
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

server:
  port: 6666
